### PR TITLE
New sheet design

### PR DESCRIPTION
**Pull request by patrys**
- New character sheet design
- Support for current/max bonus on all items (migration should update existing data)
- Automatic total armor calculation
- Support for Calendar/Weather add-on (automatically configured for Forbidden Lands if installed)
- Support for vtta-tokenizer add-on (clicking on portraits will bring up the token image editor if installed)
- Support for rollable macros in item fields (example: create a critical wound with healing time set to `[[d6]] days` and it will replace it with a roll once dragged onto a character)

The paper frame comes from the [Roll 20 character sheet](https://github.com/Roll20/roll20-character-sheets/tree/master/Forbidden_Lands) released under MIT.

image

### CODE REVIEW

**Comment by Perfectro** [comment]
Nice, thank you for this !
Do you mind making me a list with all the new asset and their license ?

**Comment by patrys** [comment]
Sure:
- the paper border image comes from here: https://github.com/Roll20/roll20-character-sheets/blob/master/Forbidden_Lands/images/FBL%20small%20border%20box.png (repository is under MIT, committer did not mention whether it's their original work)
- IM Fell Great Primer fonts are under SIL Open Font License: https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL

**Comment by patrys** [comment]
Thanks for reviewing it, I know item model sheets are weird now, they need a redesign after bonus was split. I'll fix the bugs you found and I'm going to use it in a session and try to get feedback from players too.

**Comment by patrys** [comment]
@Perfectro I have a questio related to code formatting: I have my IDE configured to automatically format files on save, is there a formatting tool (and config) you use or want to use?

**Comment by Perfectro** [comment]
Of course. Nothing fancy on my side, just the default configuration of IntelliJ
An editorconfig of it : https://gist.github.com/Perfectro/1dc83193bc93d007d2bb8ffe21449929
I don't mind using something in particular. Just that some of your formatting make the code really hard to read.
Like this one :
```
sendWeaponToChat(weapon) {
    let message =
      "<b>" +
      weapon.name.toUpperCase() +
      "</b></br>" +
      "<b>" +
      game.i18n.localize("WEAPON.CATEGORY") +
      ": </b>" +
      weapon.data.data.category +
      "</br>" +
      "<b>" +
      game.i18n.localize("WEAPON.GRIP") +
      ": </b>" +
      weapon.data.data.grip +
      "</br>" +
      "<b>" +
      game.i18n.localize("WEAPON.BONUS") +
      ": </b>" +
      weapon.data.data.bonus +
      "</br>" +
      "<b>" +
      game.i18n.localize("WEAPON.DAMAGE") +
      ": </b>" +
      weapon.data.data.damage +
      "</br>" +
      "<b>" +
      game.i18n.localize("WEAPON.RANGE") +
      ": </b>" +
      weapon.data.data.range +
      "</br>" +
      "<b>" +
      game.i18n.localize("WEAPON.FEATURE") +
      ": </b>" +
      weapon.data.data.features;
    let chatData = {
      user: game.user._id,
      content: message,
    };
    ChatMessage.create(chatData, {});
  }
```
Instead of
```
sendWeaponToChat(weapon) {
        let message = "<b>" + weapon.name.toUpperCase() + "</b></br>" +
            "<b>" + game.i18n.localize("WEAPON.CATEGORY") + ": </b>" + weapon.data.data.category + "</br>" +
            "<b>" + game.i18n.localize("WEAPON.GRIP") + ": </b>" + weapon.data.data.grip + "</br>" +
            "<b>" + game.i18n.localize("WEAPON.BONUS") + ": </b>" + weapon.data.data.bonus + "</br>" +
            "<b>" + game.i18n.localize("WEAPON.DAMAGE") + ": </b>" + weapon.data.data.damage + "</br>" +
            "<b>" + game.i18n.localize("WEAPON.RANGE") + ": </b>" + weapon.data.data.range + "</br>" +
            "<b>" + game.i18n.localize("WEAPON.FEATURE") + ": </b>" + weapon.data.data.features;
        let chatData = {
            user: game.user._id,
            content: message
        };
        ChatMessage.create(chatData, {});
    }
```

**Comment by patrys** [comment]
I've incorporated most of your points, the gear sheets still need to be split but I want to change how items are sent to chat first as my players do that by accident a lot. I also have a plan to switch item posting to use a handlebar template.

**Comment by Perfectro** [comment]
Thanks again for this ! The sheet looks great !
Some feedback :
- The migration is off for some item, like weapon. All my weapons are without bonus now.
- It is impossible to add an artifact dice to an item. Unless I am missing something ? Before this change, it was possible to add it to the bonus field like `3+1d8`.

**Pull request merged**
